# Map sprite names to common functions
# Usage:
#   <%= icon_tag :email %>
# Generated HTML:
#   <i class="icons-famfamfam-email_go"></i>
email: 'icons-famfamfam-email_go'
arrow_right: 'icon-chevron-right'
arrow_down: 'icon-chevron-down'